// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9HiG3-WHPy7REPYUq64GegxQSQ3PB4j0',
    appId: '1:929354417131:web:f57ca0f42bdf01b0d30fae',
    messagingSenderId: '929354417131',
    projectId: 'usus-611b4',
    authDomain: 'usus-611b4.firebaseapp.com',
    databaseURL: 'https://usus-611b4-default-rtdb.firebaseio.com',
    storageBucket: 'usus-611b4.appspot.com',
    measurementId: 'G-S1CWVSEGQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbn0nY9GHkNZSqMzWItatiNmKBETN5WYI',
    appId: '1:929354417131:android:3836ec29b0e6d4add30fae',
    messagingSenderId: '929354417131',
    projectId: 'usus-611b4',
    databaseURL: 'https://usus-611b4-default-rtdb.firebaseio.com',
    storageBucket: 'usus-611b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgSBwTjNHHQhmrq3fDFfar3oLzmzj60_g',
    appId: '1:929354417131:ios:84ba068276ac4df0d30fae',
    messagingSenderId: '929354417131',
    projectId: 'usus-611b4',
    databaseURL: 'https://usus-611b4-default-rtdb.firebaseio.com',
    storageBucket: 'usus-611b4.appspot.com',
    iosClientId: '929354417131-4fi812je5684qt0msfes5md9gucli4d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgSBwTjNHHQhmrq3fDFfar3oLzmzj60_g',
    appId: '1:929354417131:ios:84ba068276ac4df0d30fae',
    messagingSenderId: '929354417131',
    projectId: 'usus-611b4',
    databaseURL: 'https://usus-611b4-default-rtdb.firebaseio.com',
    storageBucket: 'usus-611b4.appspot.com',
    iosClientId: '929354417131-4fi812je5684qt0msfes5md9gucli4d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
